apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-dev
  template:
    metadata:
      labels:
        app: kibana-dev
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.1
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-dev:9200"
          ports:
            - containerPort: 5601
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-dev
spec:
  selector:
    app: kibana-dev
  ports:
  - port: 5601
    targetPort: 5601
  type: LoadBalancer