apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  namespace: backend
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: LoadBalancer
