apiVersion: v1
kind: Pod
metadata:
  name: order-server-pod
  namespace: backend
spec:
  containers:
  - name: order-server-container
    image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/order-server
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - host-172-16-18-75
            - host-172-16-19-178
