apiVersion: apps/v1
kind: Deployment
metadata:
  name: faq-server-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faq-server
  template:
    metadata:
      labels:
        app: faq-server
    spec:
      containers:
      - name: faq-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/faq-server
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
