apiVersion: v1
kind: Service
metadata:
  name: notification-server-service
  namespace: backend
spec:
  selector:
    app: notification-server
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8080
  type: ClusterIP
