apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-server-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-server-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
