apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eureka-server-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eureka-server-deployment-dev
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
