apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-server-deployment
  namespace: backend
spec:
  revisionHistoryLimit: 5
  replicas: 5 
  selector:
    matchLabels:
      app: item-server
  template:
    metadata:
      labels:
        app: item-server
    spec:
      containers:
      - name: item-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/item-server:0.8.8
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Seoul"
        resources:
          requests:
            cpu: "10m"
            memory: "500Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
      terminationGracePeriodSeconds: 15