apiVersion: v1
kind: Service
metadata:
  name: item-server-service
  namespace: backend
spec:
  selector:
    app: item-server
  ports:
    - protocol: TCP
      port: 85
      targetPort: 8080
  type: ClusterIP
