apiVersion: v1
kind: Service
metadata:
  name: seller-server-service
  namespace: backend
spec:
  selector:
    app: seller-server
  ports:
    - protocol: TCP
      port: 88
      targetPort: 8080
  type: ClusterIP
