apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-server-deployment
  namespace: backend
  annotations:
    revision: "5" # git에서 버전 관리가 되기 때문에 default보다 낮게 설정
spec:
  replicas: 3 # prod 단계에서 3으로 변경
  selector:
    matchLabels:
      app: seller-server
  template:
    metadata:
      labels:
        app: seller-server
    spec:
      containers:
      - name: seller-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/seller-server:0.1.6
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Seoul"
        resources:
          # limits:
            # cpu: "100m"
            # memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "500Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
      ## prod 단계에서 주석 제거
      # terminationGracePeriodSeconds: 15 ## 파드 종료 시간 설정