apiVersion: v1
kind: Service
metadata:
  name: event-server-service
  namespace: backend
spec:
  selector:
    app: event-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
