apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-server-deployment
  namespace: backend
  annotations:
    revision: "5" # git에서 버전 관리가 되기 때문에 default보다 낮게 설정
spec:
  replicas: 1 # prod 단계에서 3으로 변경
  selector:
    matchLabels:
      app: event-server
  template:
    metadata:
      labels:
        app: event-server
    spec:
      containers:
      - name: event-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/event-server:0.3.3
        ports:
        - containerPort: 8080

        # resources:
        #   limits:
        #     cpu: "0.03"
        #     memory: "400Mi"
        #   requests:
        #     cpu: "0.003" # 모니터링 상 평균 0.003 CPU usage를 가짐
        #     memory: "200Mi"
        # readinessProbe:
        #   httpGet:
        #     path: /healthz  # 애플리케이션의 상태를 체크할 endpoint path
        #     port: 8080
        #   initialDelaySeconds: 5  # 컨테이너 시작 후 readinessProbe 시작까지의 대기 시간
        #   periodSeconds: 10 # readinessProbe을 실행하는 시간 간격
        #   failureThreshold: 4 # readinessProbe 실패로 간주되는 실패 횟수
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
      ## prod 단계에서 주석 제거
      # terminationGracePeriodSeconds: 15 ## 파드 종료 시간 설정