apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  namespace: backend
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
