apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
      - name: gateway-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/gateway-server:0.2.2
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
