apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-server
  template:
    metadata:
      labels:
        app: notification-server
    spec:
      containers:
      - name: notification-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/notification-server:0.1.0
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
