apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-server-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-server
  template:
    metadata:
      labels:
        app: order-server
    spec:
      containers:
      - name: order-server-container
        image: dpang-shop-dev.kr-gov-central-1.kcr.dev/dpang-backend/order-server:latest
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - backend
