apiVersion: v1
kind: Service
metadata:
  name: order-server-service
  namespace: backend
spec:
  selector:
    app: order-server
  ports:
    - protocol: TCP
      port: 86
      targetPort: 8080
  type: ClusterIP
