apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elasticsearch
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      jdbc {
        jdbc_driver_library => "/path/to/mysql-connector-java.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://172.16.213.44:3306/ShopDB"
        jdbc_user => "root"
        jdbc_password => "Dpang123!"
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
      }
    }
