apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elasticsearch
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      jdbc {
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.3.0-bin.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://az-a.dpang-database.70e895c2d22b44e79797ed89d4dc2b5c.mysql.managed-service.kr-gov-central-1.kakaocloud-kr-gov.com:3306/dpang_mileage"
        jdbc_user => "admin"
        jdbc_password => "PwUYtotGFZVdDKrY"
        statement => "SELECT * FROM mileage"
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "shopindex"
      }
    }
