apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elasticsearch
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 9600
      targetPort: 9600
  type: ClusterIP
