apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch-dev
  template:
    metadata:
      labels:
        app: elasticsearch-dev
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          env:
            - name: discovery.type
              value: "single-node"
          ports:
            - containerPort: 9200
            - containerPort: 9300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-dev
spec:
  selector:
    app: elasticsearch-dev
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP