apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-dev
  template:
    metadata:
      labels:
        app: logstash-dev
    spec:
      volumes:
      - name: connector-dir
        emptyDir: {}
      - name: logstash-config-volume
        configMap:
          name: logstash-config
      initContainers:
      - name: download-connector
        image: appropriate/curl:latest
        command:
        - sh
        - -c
        - |
          curl -L -o /connector-dir/mysql-connector-java.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar
        volumeMounts:
        - name: connector-dir
          mountPath: /connector-dir
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.10.2
          ports:
            - containerPort: 9600
          volumeMounts:
          - name: connector-dir
            mountPath: /usr/share/logstash/logstash-core/lib/jars/mysql-connector-java.jar
            subPath: mysql-connector-java.jar
          - name: logstash-config-volume
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: logstash-config-volume
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-dev
spec:
  selector:
    app: logstash-dev
  ports:
    - protocol: TCP
      port: 9600
      targetPort: 9600
  type: ClusterIP
